// Push files generated by Prometheus/E2B to a GitHub repo.
// Uses the GitHub Contents API (no git CLI needed).
// Requires GITHUB_TOKEN with repo scope in env.

export interface PushFile {
  path: string;   // relative path inside the project folder, e.g. "index.html"
  content: string;
}

export interface PushResult {
  repoUrl: string;
  commitUrl: string;
  pagesUrl: string | null;  // null until GitHub Pages finishes building (~1 min)
  files: string[];
}

const GITHUB_API = "https://api.github.com";
const DEFAULT_REPO = "osman-jalloh-lab/prometheus-builds";

export function githubConnected(): boolean {
  return !!process.env.GITHUB_TOKEN;
}

async function ghFetch(path: string, method: string, body?: unknown): Promise<Response> {
  return fetch(`${GITHUB_API}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      "User-Agent": "hermes-os-prometheus",
    },
    body: body ? JSON.stringify(body) : undefined,
    signal: AbortSignal.timeout(15_000),
  });
}

async function ensureRepoExists(owner: string, repo: string): Promise<void> {
  const check = await ghFetch(`/repos/${owner}/${repo}`, "GET");
  if (check.status === 200) return;
  if (check.status !== 404) throw new Error(`GitHub repo check returned ${check.status}`);

  const create = await ghFetch("/user/repos", "POST", {
    name: repo,
    description: "Projects built by Prometheus — Hermes OS idea forge",
    private: false,
    auto_init: true,
  });
  if (!create.ok) {
    const err = (await create.json().catch(() => ({}))) as { message?: string };
    throw new Error(`Failed to create repo: ${err.message ?? create.status}`);
  }
  // Wait for GitHub to initialize the default branch
  await new Promise((r) => setTimeout(r, 2500));
}

// Enable GitHub Pages on the repo (serves from root of main branch).
// Idempotent — safe to call on every push, returns existing URL if already enabled.
async function ensureGitHubPages(owner: string, repo: string): Promise<string> {
  const pagesUrl = `https://${owner}.github.io/${repo}`;

  // Check if already enabled
  const check = await ghFetch(`/repos/${owner}/${repo}/pages`, "GET");
  if (check.status === 200) return pagesUrl;

  // Enable it
  const enable = await ghFetch(`/repos/${owner}/${repo}/pages`, "POST", {
    source: { branch: "main", path: "/" },
  });

  if (!enable.ok && enable.status !== 409) {
    // 409 = already exists, that's fine
    console.warn(`[github-push] Pages enable returned ${enable.status} — continuing`);
  }

  return pagesUrl;
}

async function getFileSha(owner: string, repo: string, path: string): Promise<string | undefined> {
  const res = await ghFetch(`/repos/${owner}/${repo}/contents/${path}`, "GET");
  if (res.status === 404) return undefined;
  if (!res.ok) return undefined;
  const data = (await res.json()) as { sha?: string };
  return data.sha;
}

// Detects whether the file list looks like a website (has index.html).
function isWebsite(files: PushFile[]): boolean {
  return files.some((f) => f.path === "index.html" || f.path.endsWith("/index.html"));
}

export async function pushToGitHub(
  files: PushFile[],
  opts?: {
    repo?: string;          // default: osman-jalloh-lab/prometheus-builds
    folder?: string;        // subfolder, e.g. "fresh-cuts-barbershop"
    commitMessage?: string;
  }
): Promise<PushResult> {
  if (!process.env.GITHUB_TOKEN) {
    throw new Error("GITHUB_TOKEN is not set. Add it to Vercel env vars (needs repo scope).");
  }

  const repoFull = opts?.repo ?? DEFAULT_REPO;
  const [owner, repo] = repoFull.split("/");
  const folder = opts?.folder ?? `build-${Date.now()}`;
  const message = opts?.commitMessage ?? `feat: Prometheus build — ${folder}`;

  await ensureRepoExists(owner, repo);

  const pushed: string[] = [];

  for (const file of files) {
    const repoPath = `${folder}/${file.path}`;
    const sha = await getFileSha(owner, repo, repoPath);
    const encoded = Buffer.from(file.content, "utf-8").toString("base64");

    const res = await ghFetch(`/repos/${owner}/${repo}/contents/${repoPath}`, "PUT", {
      message,
      content: encoded,
      ...(sha ? { sha } : {}),
    });

    if (!res.ok) {
      const err = (await res.json().catch(() => ({}))) as { message?: string };
      throw new Error(`Failed to push ${repoPath}: ${err.message ?? res.status}`);
    }

    pushed.push(repoPath);
  }

  // Enable GitHub Pages if the build contains a website
  let pagesUrl: string | null = null;
  if (isWebsite(files)) {
    const base = await ensureGitHubPages(owner, repo);
    // URL to the specific project folder
    pagesUrl = `${base}/${folder}/`;
  }

  return {
    repoUrl: `https://github.com/${owner}/${repo}/tree/main/${folder}`,
    commitUrl: `https://github.com/${owner}/${repo}/commits/main`,
    pagesUrl,
    files: pushed,
  };
}
